
  
# -- Path for to the `opsgenie_apikey` in vault. They key must be named `slack_webhook`. The path can be anything ex. `secret/kv-v2-glueops/notifications`
vault_path: nil

slack:
  # -- Leave this value as `nil` if you provided a `vault_path`. Otherwise, this value must be set. You CANNOT have a `vault_path` and `slack.webhook` defined at the same time.
  webhook: nil
  # -- The slack channel you want alerts sent to.
  channel: "#alerts"

# -- These labels are additional filters you can use to keep these notifications for one particular team, component, or alert. Note: you must set the same filters (with the exception of alertname) on the alert definition itself. The alert definition is also refered to as the prometheusrule.
labels:
  team: nil
  component: nil
  alertname: nil

# -- Amount of time to fire an alert again after the first one is sent.
route:
  repeatInterval: "360m"
  groupInterval: "360m"
